# Runxel's Archicad Wiki
# Jekyll config for
# https://github.com/runxel/archicad-wiki
title: Runxel's Archicad Wiki
# email: your-email@example.com
description: >-
  Runxel's Archicad Wiki liefert die besten Tipps und Tricks im täglichen
  Einsatz von Archicad.
baseurl: /archicad-wiki
# url: "https://runxel.xyz"
twitter_username: runxel
github_username:  runxel
author: Lucas Becker
lang: de

# Build settings
# remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true

# theme settings:
logo: "/assets/img/raw-logo.svg"
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
# Aux links for the upper right navigation
aux_links:
  "R·A·W auf GitHub":
    - "//github.com/runxel/archicad-wiki"
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; Lucas Becker // Veröffentlicht unter <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY-NC-SA</a>. // Alle Warenzeichen auf dieser Seite sind Eigentum ihrer jeweiligen Inhaber."
# Google Analytics [disabled for now]
# ga_tracking: UA-5555555-55

# seo
# see also https://jekyll.github.io/jekyll-seo-tag/usage/
tagline: Die besten Tipps und Tricks zum Arbeiten in Archicad.
twitter:
  username: runxel
  card: summary

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
