# Runxel's Archicad Wiki
# Jekyll config for
# https://github.com/runxel/archicad-wiki
title: Runxel's Archicad Wiki
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Runxel's Archicad Wiki liefert die besten Tipps und Tricks im täglichen
  Einsatz von Archicad.
baseurl: /archicad-wiki
# url: "https://runxel.xyz"
twitter_username: runxel
github_username:  runxel

# Build settings
remote_theme: pmarsceill/just-the-docs

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
